-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyCaloriesGoal" DOUBLE PRECISION NOT NULL DEFAULT 2000,
ADD COLUMN     "dailySleepGoal" DOUBLE PRECISION NOT NULL DEFAULT 8,
ADD COLUMN     "dailyWaterGoal" DOUBLE PRECISION NOT NULL DEFAULT 2500,
ADD COLUMN     "dailyWorkoutGoal" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "height" DOUBLE PRECISION,
ADD COLUMN     "weight" DOUBLE PRECISION;
